version: '3'

services: 
  mongo: 
    image: mongo
    restart: always
    ports: 
     - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: url_shortener
      MONGO_INITDB_ROOT_USERNAME: gusein
      MONGO_INITDB_ROOT_PASSWORD: 12345
  server:   
    build:
      context: ./
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DB_LOCAL=mongodb://gusein:12345@mongo:27017/
      - NODE_ENV=production
      - CLIENT_URL=http://localhost:3000